#!/usr/bin/env python3
"""
PyPI 构建脚本 — 为 skills/agents 生成 wheel 包
由 .github/workflows/publish-pypi.yml 调用

用法: pypi-build.py <type> <name> <version> <pypi_name>
示例: pypi-build.py agents rag-assistant 1.0.0 rag-assistant-ldxs
示例: pypi-build.py skills git-sync 2.27.1 git-sync-ldxs
"""
import os
import sys
import shutil
import subprocess
import tempfile

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def build_agent(name, version, pypi_name):
    """构建 agent 包 — agent 已有 main.py + package/ 结构"""
    src_dir = os.path.join(REPO_ROOT, "agent", name)
    build_dir = os.path.join(tempfile.gettempdir(), f"pypi_build_agent_{name}_{version}")

    if os.path.exists(build_dir):
        shutil.rmtree(build_dir)
    os.makedirs(build_dir)

    # 确定包目录名
    pkg_dir_name = name.replace("-", "_")  # rag-assistant -> rag_assistant

    # 拷贝 main.py + 包目录 + key 文件
    for item in ["main.py", pkg_dir_name, "requirements.txt", "README.md", "LICENSE", "CHANGELOG.md"]:
        src = os.path.join(src_dir, item)
        if os.path.exists(src):
            dst = os.path.join(build_dir, item)
            if os.path.isdir(src):
                shutil.copytree(src, dst)
            else:
                shutil.copy2(src, dst)

    # 确保 package 目录下有 __version__
    init_file = os.path.join(build_dir, pkg_dir_name, "__init__.py")
    if os.path.exists(init_file):
        with open(init_file, "r", encoding="utf-8") as f:
            content = f.read()
        if "__version__" not in content:
            with open(init_file, "a", encoding="utf-8") as f:
                f.write(f'\n__version__ = "{version}"\n')
    else:
        os.makedirs(os.path.dirname(init_file), exist_ok=True)
        with open(init_file, "w", encoding="utf-8") as f:
            f.write(f'__version__ = "{version}"\n')

    # 生成 setup.py
    setup_py = f'''"""setup.py for {name} — auto-generated by pypi-build"""
from setuptools import setup, find_packages
import os

pkg_dir = "{pkg_dir_name}"
init_file = os.path.join(os.path.dirname(__file__), pkg_dir, "__init__.py")
with open(init_file) as f:
    for line in f:
        if line.startswith("__version__"):
            VERSION = line.split('"')[1]
            break
    else:
        VERSION = "{version}"

req_path = os.path.join(os.path.dirname(__file__), "requirements.txt")
REQUIREMENTS = []
if os.path.exists(req_path):
    with open(req_path, encoding="utf-8") as f:
        REQUIREMENTS = [l.strip() for l in f if l.strip() and not l.startswith("#")]

readme_path = os.path.join(os.path.dirname(__file__), "README.md")
if os.path.exists(readme_path):
    with open(readme_path, encoding="utf-8") as f:
        LONG_DESC = f.read()
else:
    LONG_DESC = "{name}: AI Agent"

setup(
    name="{pypi_name}",
    version=VERSION,
    description="{name} — AI Agent",
    long_description=LONG_DESC,
    long_description_content_type="text/markdown",
    author="Ldxs (wUwproject)",
    author_email="wuwofc@yeah.net",
    url="https://github.com/Ldxs001/workbuddy-skills",
    packages=find_packages(include=["{pkg_dir_name}", "{pkg_dir_name}.*"]),
    include_package_data=True,
    python_requires=">=3.10",
    install_requires=REQUIREMENTS,
    entry_points={{"console_scripts": ["{pypi_name}=main:main"]}},
    # 版本含 b/alpha/beta/rc/dev → Beta，否则 Production/Stable
    _is_beta = any(x in VERSION.lower() for x in ['b', 'alpha', 'beta', 'rc', 'dev'])
    classifiers=[
        f"Development Status :: {'4 - Beta' if _is_beta else '5 - Production/Stable'}",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
'''

    with open(os.path.join(build_dir, "setup.py"), "w", encoding="utf-8") as f:
        f.write(setup_py)

    _build_wheel(build_dir, pypi_name, version)


def build_skill(name, version, pypi_name):
    """构建 skill 包 — skill 的 scripts/ 目录作为 Python 包发布"""
    src_dir = os.path.join(REPO_ROOT, "skills", name)
    scripts_dir = os.path.join(src_dir, "scripts")

    if not os.path.isdir(scripts_dir):
        print(f"  ❌ scripts/ not found in skills/{name}")
        sys.exit(1)

    build_dir = os.path.join(tempfile.gettempdir(), f"pypi_build_skill_{name}_{version}")

    if os.path.exists(build_dir):
        shutil.rmtree(build_dir)
    os.makedirs(build_dir)

    # PyPI 包名用下划线
    pkg_dir_name = pypi_name.replace("-", "_")

    # 将 scripts/ 全部拷贝到包目录下
    pkg_dir = os.path.join(build_dir, pkg_dir_name)
    shutil.copytree(scripts_dir, pkg_dir)

    # 确保有 __init__.py
    init_file = os.path.join(pkg_dir, "__init__.py")
    if not os.path.exists(init_file):
        with open(init_file, "w", encoding="utf-8") as f:
            f.write(f'__version__ = "{version}"\n')
    else:
        with open(init_file, "r", encoding="utf-8") as f:
            content = f.read()
        if "__version__" not in content:
            with open(init_file, "a", encoding="utf-8") as f:
                f.write(f'\n__version__ = "{version}"\n')

    # 读 _meta.json 获取描述
    meta_path = os.path.join(src_dir, "_meta.json")
    description = f"{name} — WorkBuddy Skill"
    if os.path.exists(meta_path):
        import json
        with open(meta_path, encoding="utf-8") as f:
            meta = json.load(f)
        description = meta.get("description", description)

    # 生成 setup.py
    setup_py = f'''"""setup.py for {name} — auto-generated by pypi-build"""
from setuptools import setup, find_packages
import os

pkg_dir = "{pkg_dir_name}"
init_file = os.path.join(os.path.dirname(__file__), pkg_dir, "__init__.py")
with open(init_file) as f:
    for line in f:
        if line.startswith("__version__"):
            VERSION = line.split('"')[1]
            break
    else:
        VERSION = "{version}"

setup(
    name="{pypi_name}",
    version=VERSION,
    description="{description}",
    author="Ldxs (wUwproject)",
    author_email="wuwofc@yeah.net",
    url="https://github.com/Ldxs001/workbuddy-skills",
    packages=find_packages(include=["{pkg_dir_name}", "{pkg_dir_name}.*"]),
    include_package_data=True,
    python_requires=">=3.10",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
    ],
)
'''

    with open(os.path.join(build_dir, "setup.py"), "w", encoding="utf-8") as f:
        f.write(setup_py)

    _build_wheel(build_dir, pypi_name, version)


def _build_wheel(build_dir, pypi_name, version):
    """在 build_dir 下构建 wheel 并复制到工作区 dist/"""
    print(f"  Building {pypi_name} v{version}...")

    result = subprocess.run(
        [sys.executable, "-m", "build", "--wheel", build_dir],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"  ❌ Build failed: {result.stderr[:500]}")
        sys.exit(1)

    # 复制 wheel 到工作区 dist/
    dist_src = os.path.join(build_dir, "dist")
    dist_dst = os.path.join(os.getcwd(), "dist")
    os.makedirs(dist_dst, exist_ok=True)

    for fname in os.listdir(dist_src):
        if fname.endswith(".whl"):
            shutil.copy2(os.path.join(dist_src, fname), os.path.join(dist_dst, fname))
            print(f"  ✅ Wheel: {fname}")

    # 清理
    shutil.rmtree(build_dir, ignore_errors=True)


def main():
    if len(sys.argv) < 5:
        print("用法: pypi-build.py <type> <name> <version> <pypi_name>")
        sys.exit(1)

    pkg_type = sys.argv[1]
    name = sys.argv[2]
    version = sys.argv[3]
    pypi_name = sys.argv[4]

    print(f":: PyPI Build — {pkg_type}/{name} v{version} -> {pypi_name}")

    if pkg_type in ("agent", "agents"):
        build_agent(name, version, pypi_name)
    elif pkg_type == "skills":
        build_skill(name, version, pypi_name)
    else:
        print(f"  ❌ Unknown type: {pkg_type}")
        sys.exit(1)

    print(f"  ✅ Done. Wheels ready in dist/")


if __name__ == "__main__":
    main()
